### ISSUE TITLE
Drag-and-drop re-ordering

### ISSUE THREAD

**Issue by DarthMarauder** [ColdTrick/tag_tools#1]
The tag boxes can't be dragged for re-ordering (in elgg 1.9.4). This is needed if an user wants their tags to be in a specific order, for whatever reason. Now they need to delete every tag first if they want to add a tag in the beginning.

**Comment by jdalsem** [comment]
Would indeed be nice. Need this first https://github.com/aehlke/tag-it/issues/175

**Comment by jdalsem** [comment]
the tag javascript features have been moved to core. Currently drag/drop is not enabled in the core tag features. It should however be possible: https://github.com/yairEO/tagify#drag--sort
