### ISSUE TITLE
'page_top' notifications not sent if 'search_advanced' plugin is activated

### ISSUE THREAD

**Issue by oseg** [ColdTrick/tag_tools#15]
There is a conflict between 'tag_tools' and 'search_advanced' plugins:

In tag_tools_get_notification_type_subtypes(),  get_registered_entity_types() is called but in search_advanced_init(), elgg_unregister_entity_type('object', 'page_top'); is called...

Until a proper fix is implemented in tag_tools or search_advanced plugin, a workaround could be implemented in tag_tools_init() by registering for 'notification_type_subtype' hook:

```
function tag_tools_init() {
...
elgg_register_plugin_hook_handler('notification_type_subtype', 'tag_tools', 'tag_tools_add_page_top_subtype_in_notifications');
...
}

function tag_tools_add_page_top_subtype_in_notifications($hook, $type, $return_value, $params) {
	if (empty($return_value) || !is_array($return_value)) {
	    return;
	}

	if (!elgg_is_active_plugin('pages')) {
	    return;
	}

	if( in_array('page_top', $return_value['object'])) {
	    return;
	}

	$return_value['object'][] = 'page_top';

	return $return_value;
}

```

**Comment by jdalsem** [comment]
In Elgg 3.0 there is no longer a distinction between `page_top` and regulare `page` object. That change will make these ugly hacks in tag_tools and search_advanced obsolete. Until then we need to live with this situation
