### ISSUE TITLE
check for new version of tag-it.js

### ISSUE THREAD

**Issue by jeabakker** [ColdTrick/tag_tools#4]
reason: https://github.com/ColdTrick/tag_tools/blob/1305a03e4e5268e09ce83d9e242c21239d33f65e/vendors/jquery/tag_it/js/tag-it.js#L129

is no longer supported by modern versions of jquery

**Comment by jdalsem** [comment]
There is no newer stable:
- https://github.com/aehlke/tag-it
- https://asset-packagist.org/package/bower-asset/tag-it
