### ISSUE TITLE
Profile manager tag fields not taken into account in tags suggestion (autocomplete)

### ISSUE THREAD

**Issue by oseg** [ColdTrick/tag_tools#7]
**Title**: Profile manager tag fields not taken into account in tags suggestion (autocomplete)
**Context**: elgg v1.12.9 + profile manager v9.1 + tag tools v1.4 + other 3dr party plugins
**Scenario**:
1. In profile manager settings, create a new user profile field "area of interest" 
2. Set "area of interest" field type as "tags"
3. Edit a user profile page, add "movies" in "area of interest" field
4. Edit another user profile page, in the "area of interest" field, enter "mo"
=> the "movies" tag is not suggested

Same issue with group profile tag fields

Possible workaround in procedures/autocomplete.php by adding $profile_area_of_interest_id in the WHERE condition of the SQL request

```
<?php

elgg_gatekeeper();

$query = get_input('q');

$result = [];

if (!empty($query)) {

    $dbprefix = elgg_get_config('dbprefix');
    $tags_id = elgg_get_metastring_id('tags');
    $profile_area_of_interest_id = elgg_get_metastring_id("profile_area_of_interest");

    $sql = "SELECT msv.string as string, count(*) as total";
    $sql .= " FROM {$dbprefix}metadata md";
    $sql .= " JOIN {$dbprefix}metastrings msv ON md.value_id = msv.id";
    $sql .= " WHERE (md.name_id = " . $tags_id . " OR  md.name_id = " . $profile_area_of_interest_id.")";
    $sql .= " AND msv.string LIKE '" . sanitise_string($query) . "%'";

```

**Comment by jdalsem** [comment]
We are currently only supporting the 'tags' field. No other metadata is presented in the autocomplete
