### ISSUE TITLE
strange bug: the word 'congestion' is not acceptable as a tag

### ISSUE THREAD

**Issue by propertunist** [ColdTrick/tag_tools#8]
i was just adding the word 'congestion' as a tag to a video on my site and found that no matter what i do, the system will not convert the word into a boxed tag. i can get a tag that contains every letter up to the word 'congestion' (e.g. 'congest' or 'congestio'), but not 'congestion'!

**Comment by jdalsem** [comment]
I have no problems with this specific word... do you get any javascript issues? Does it happen with different browsers?

**Comment by propertunist** [comment]
a bit more info:
- it occurs in both firefox and chromium
- there are no JS errors
- it is not the word 'congestion' that is the problem at all as i have seen it occur with other words too.

to reproduce:
add tags as normal, delete one or two and add some more (more than 1)
repeat this a few times and it is guaranteed to trigger the bug (on my site)

**Comment by jdalsem** [comment]
Unable to reproduce. In Elgg 4 the JS changed a lot around tags... maybe there you will have no issues.
